//! Default table schema definitions
//!
//! Contains built-in schemas for common Azure/Sentinel tables.

use super::types::{ColumnDef, TableInfo};
use log::info;

/// Load all default table schemas into a collection
pub fn load_defaults() -> Vec<TableInfo> {
    let mut tables = Vec::new();

    // Common base columns for most tables
    let time_col = ColumnDef::datetime("TimeGenerated");
    let tenant_col = ColumnDef::string("TenantId");

    // SecurityEvent - Windows Security logs (comprehensive schema)
    tables.push(
        TableInfo::canonical("SecurityEvent")
            .source("sentinel")
            .description("Security events collected from Windows machines")
            .column(time_col.clone())
            .column(tenant_col.clone())
            .with_column("AccessMask", "string")
            .with_column("Account", "string")
            .with_column("AccountDomain", "string")
            .with_column("AccountExpires", "string")
            .with_column("AccountName", "string")
            .with_column("AccountSessionIdentifier", "string")
            .with_column("AccountType", "string")
            .with_column("Activity", "string")
            .with_column("AdditionalInfo", "string")
            .with_column("AdditionalInfo2", "string")
            .with_column("AuthenticationPackageName", "string")
            .with_column("CallerProcessId", "string")
            .with_column("CallerProcessName", "string")
            .with_column("Channel", "string")
            .with_column("ClientAddress", "string")
            .with_column("ClientIPAddress", "string")
            .with_column("ClientName", "string")
            .with_column("CommandLine", "string")
            .with_column("Computer", "string")
            .with_column("DCDNSName", "string")
            .with_column("DeviceDescription", "string")
            .with_column("DeviceId", "string")
            .with_column("DomainName", "string")
            .with_column("ElevatedToken", "string")
            .with_column("ErrorCode", "int")
            .with_column("EventData", "string")
            .with_column("EventID", "int")
            .with_column("EventLevelName", "string")
            .with_column("EventRecordId", "string")
            .with_column("EventSourceName", "string")
            .with_column("FailureReason", "string")
            .with_column("FileHash", "string")
            .with_column("FilePath", "string")
            .with_column("HandleId", "string")
            .with_column("IpAddress", "string")
            .with_column("IpPort", "string")
            .with_column("KeyLength", "int")
            .with_column("Level", "string")
            .with_column("LmPackageName", "string")
            .with_column("LogonGuid", "string")
            .with_column("LogonID", "string")
            .with_column("LogonProcessName", "string")
            .with_column("LogonType", "int")
            .with_column("LogonTypeName", "string")
            .with_column("MemberName", "string")
            .with_column("MemberSid", "string")
            .with_column("NewProcessId", "string")
            .with_column("NewProcessName", "string")
            .with_column("ObjectName", "string")
            .with_column("ObjectServer", "string")
            .with_column("ObjectType", "string")
            .with_column("PackageName", "string")
            .with_column("ParentProcessName", "string")
            .with_column("PrivilegeList", "string")
            .with_column("Process", "string")
            .with_column("ProcessId", "string")
            .with_column("ProcessName", "string")
            .with_column("Properties", "string")
            .with_column("SourceComputerId", "string")
            .with_column("SourceSystem", "string")
            .with_column("Status", "string")
            .with_column("SubcategoryGuid", "string")
            .with_column("SubcategoryId", "string")
            .with_column("Subject", "string")
            .with_column("SubjectAccount", "string")
            .with_column("SubjectDomainName", "string")
            .with_column("SubjectLogonId", "string")
            .with_column("SubjectUserName", "string")
            .with_column("SubjectUserSid", "string")
            .with_column("SubStatus", "string")
            .with_column("TargetAccount", "string")
            .with_column("TargetDomainName", "string")
            .with_column("TargetInfo", "string")
            .with_column("TargetLinkedLogonId", "string")
            .with_column("TargetLogonGuid", "string")
            .with_column("TargetLogonId", "string")
            .with_column("TargetServerName", "string")
            .with_column("TargetSid", "string")
            .with_column("TargetUser", "string")
            .with_column("TargetUserName", "string")
            .with_column("TargetUserSid", "string")
            .with_column("Task", "int")
            .with_column("TokenElevationType", "string")
            .with_column("TransmittedServices", "string")
            .with_column("Type", "string")
            .with_column("UserAccountControl", "string")
            .with_column("UserPrincipalName", "string")
            .with_column("VirtualAccount", "string")
            .with_column("Workstation", "string")
            .with_column("WorkstationName", "string"),
    );

    // SigninLogs - Azure AD sign-in logs (comprehensive schema)
    tables.push(
        TableInfo::canonical("SigninLogs")
            .source("sentinel")
            .description("Azure AD sign-in logs")
            .column(time_col.clone())
            .with_column("AADTenantId", "string")
            .with_column("AlternateSignInName", "string")
            .with_column("AppDisplayName", "string")
            .with_column("AppId", "string")
            .with_column("AppOwnerTenantId", "string")
            .with_column("AuthenticationDetails", "string")
            .with_column("AuthenticationMethodsUsed", "string")
            .with_column("AuthenticationProcessingDetails", "string")
            .with_column("AuthenticationProtocol", "string")
            .with_column("AuthenticationRequirement", "string")
            .with_column("AuthenticationRequirementPolicies", "string")
            .with_column("AutonomousSystemNumber", "string")
            .with_column("Category", "string")
            .with_column("ClientAppUsed", "string")
            .with_column("ConditionalAccessPolicies", "dynamic")
            .with_column("ConditionalAccessStatus", "string")
            .with_column("CorrelationId", "string")
            .with_column("CreatedDateTime", "datetime")
            .with_column("CrossTenantAccessType", "string")
            .with_column("DeviceDetail", "dynamic")
            .with_column("DurationMs", "long")
            .with_column("FlaggedForReview", "bool")
            .with_column("HomeTenantId", "string")
            .with_column("Id", "string")
            .with_column("Identity", "string")
            .with_column("IPAddress", "string")
            .with_column("IPAddressFromResourceProvider", "string")
            .with_column("IsInteractive", "bool")
            .with_column("IsRisky", "bool")
            .with_column("IsTenantRestricted", "bool")
            .with_column("Level", "string")
            .with_column("Location", "string")
            .with_column("LocationDetails", "dynamic")
            .with_column("MfaDetail", "dynamic")
            .with_column("NetworkLocationDetails", "string")
            .with_column("OperationName", "string")
            .with_column("OriginalRequestId", "string")
            .with_column("ProcessingTimeInMilliseconds", "string")
            .with_column("ResourceDisplayName", "string")
            .with_column("ResourceId", "string")
            .with_column("ResourceIdentity", "string")
            .with_column("ResourceServicePrincipalId", "string")
            .with_column("ResourceTenantId", "string")
            .with_column("ResultDescription", "string")
            .with_column("ResultSignature", "string")
            .with_column("ResultType", "string")
            .with_column("RiskDetail", "string")
            .with_column("RiskEventTypes", "string")
            .with_column("RiskEventTypes_V2", "string")
            .with_column("RiskLevel", "string")
            .with_column("RiskLevelAggregated", "string")
            .with_column("RiskLevelDuringSignIn", "string")
            .with_column("RiskState", "string")
            .with_column("ServicePrincipalId", "string")
            .with_column("ServicePrincipalName", "string")
            .with_column("SessionId", "string")
            .with_column("SignInIdentifier", "string")
            .with_column("SignInIdentifierType", "string")
            .with_column("SourceSystem", "string")
            .with_column("Status", "dynamic")
            .with_column("TokenIssuerName", "string")
            .with_column("TokenIssuerType", "string")
            .with_column("Type", "string")
            .with_column("UniqueTokenIdentifier", "string")
            .with_column("UserAgent", "string")
            .with_column("UserDisplayName", "string")
            .with_column("UserId", "string")
            .with_column("UserPrincipalName", "string")
            .with_column("UserType", "string"),
    );

    // AADUserRiskEvents - Azure AD Identity Protection risk events
    tables.push(
        TableInfo::canonical("AADUserRiskEvents")
            .source("sentinel")
            .description("Logs generated by identity protection for Azure AD user risk events")
            .column(time_col.clone())
            .column(tenant_col.clone())
            .with_column("Activity", "string")
            .with_column("ActivityDateTime", "datetime")
            .with_column("AdditionalInfo", "dynamic")
            .with_column("CorrelationId", "string")
            .with_column("DetectedDateTime", "datetime")
            .with_column("DetectionTimingType", "string")
            .with_column("Id", "string")
            .with_column("IpAddress", "string")
            .with_column("LastUpdatedDateTime", "datetime")
            .with_column("Location", "dynamic")
            .with_column("OperationName", "string")
            .with_column("RequestId", "string")
            .with_column("RiskDetail", "string")
            .with_column("RiskEventType", "string")
            .with_column("RiskLevel", "string")
            .with_column("RiskState", "string")
            .with_column("Source", "string")
            .with_column("SourceSystem", "string")
            .with_column("TokenIssuerType", "string")
            .with_column("Type", "string")
            .with_column("UserDisplayName", "string")
            .with_column("UserId", "string")
            .with_column("UserPrincipalName", "string"),
    );

    // AzureDiagnostics - extensible table (schema varies by resource)
    tables.push(
        TableInfo::extensible("AzureDiagnostics")
            .source("sentinel")
            .description("Azure resource diagnostic logs (schema varies by resource)")
            .with_column("Category", "string")
            .with_column("CorrelationId", "string")
            .with_column("DurationMs", "string")
            .with_column("Level", "string")
            .with_column("Message", "string")
            .with_column("OperationName", "string")
            .with_column("OperationVersion", "string")
            .with_column("Resource", "string")
            .with_column("ResourceGroup", "string")
            .with_column("ResourceProvider", "string")
            .with_column("ResourceType", "string")
            .with_column("ResultDescription", "string")
            .with_column("ResultSignature", "string")
            .with_column("ResultType", "string")
            .with_column("TimeGenerated", "datetime")
            .with_column("_ResourceId", "string"),
    );

    // Syslog - Linux syslog events
    tables.push(
        TableInfo::canonical("Syslog")
            .source("sentinel")
            .description("Syslog events on Linux computers using the Log Analytics agent")
            .column(time_col.clone())
            .with_column("CollectorHostName", "string")
            .with_column("Computer", "string")
            .with_column("EventTime", "datetime")
            .with_column("Facility", "string")
            .with_column("HostIP", "string")
            .with_column("HostName", "string")
            .with_column("ProcessID", "int")
            .with_column("ProcessName", "string")
            .with_column("SeverityLevel", "string")
            .with_column("SourceSystem", "string")
            .with_column("SyslogMessage", "string")
            .with_column("Type", "string")
            .with_column("_ResourceId", "string")
            .with_column("_SubscriptionId", "string"),
    );

    // CommonSecurityLog (CEF) - comprehensive schema
    tables.push(
        TableInfo::canonical("CommonSecurityLog")
            .source("sentinel")
            .description("Common Event Format (CEF) logs from security appliances")
            .column(time_col.clone())
            .column(tenant_col.clone())
            .with_column("Activity", "string")
            .with_column("AdditionalExtensions", "string")
            .with_column("ApplicationProtocol", "string")
            .with_column("CollectorHostName", "string")
            .with_column("CommunicationDirection", "string")
            .with_column("Computer", "string")
            .with_column("DestinationDnsDomain", "string")
            .with_column("DestinationHostName", "string")
            .with_column("DestinationIP", "string")
            .with_column("DestinationMACAddress", "string")
            .with_column("DestinationNTDomain", "string")
            .with_column("DestinationPort", "int")
            .with_column("DestinationProcessId", "int")
            .with_column("DestinationProcessName", "string")
            .with_column("DestinationServiceName", "string")
            .with_column("DestinationTranslatedAddress", "string")
            .with_column("DestinationTranslatedPort", "int")
            .with_column("DestinationUserID", "string")
            .with_column("DestinationUserName", "string")
            .with_column("DestinationUserPrivileges", "string")
            .with_column("DeviceAction", "string")
            .with_column("DeviceAddress", "string")
            .with_column("DeviceCustomString1", "string")
            .with_column("DeviceCustomString1Label", "string")
            .with_column("DeviceCustomString2", "string")
            .with_column("DeviceCustomString2Label", "string")
            .with_column("DeviceCustomString3", "string")
            .with_column("DeviceCustomString3Label", "string")
            .with_column("DeviceCustomString4", "string")
            .with_column("DeviceCustomString4Label", "string")
            .with_column("DeviceCustomString5", "string")
            .with_column("DeviceCustomString5Label", "string")
            .with_column("DeviceCustomString6", "string")
            .with_column("DeviceCustomString6Label", "string")
            .with_column("DeviceDnsDomain", "string")
            .with_column("DeviceEventCategory", "string")
            .with_column("DeviceEventClassID", "string")
            .with_column("DeviceExternalID", "string")
            .with_column("DeviceFacility", "string")
            .with_column("DeviceInboundInterface", "string")
            .with_column("DeviceMacAddress", "string")
            .with_column("DeviceName", "string")
            .with_column("DeviceNtDomain", "string")
            .with_column("DeviceOutboundInterface", "string")
            .with_column("DevicePayloadId", "string")
            .with_column("DeviceProduct", "string")
            .with_column("DeviceTimeZone", "string")
            .with_column("DeviceTranslatedAddress", "string")
            .with_column("DeviceVendor", "string")
            .with_column("DeviceVersion", "string")
            .with_column("EndTime", "datetime")
            .with_column("EventCount", "int")
            .with_column("EventOutcome", "string")
            .with_column("EventType", "int")
            .with_column("ExternalID", "int")
            .with_column("FileHash", "string")
            .with_column("FileName", "string")
            .with_column("FilePath", "string")
            .with_column("FilePermission", "string")
            .with_column("FileSize", "int")
            .with_column("FileType", "string")
            .with_column("IndicatorThreatType", "string")
            .with_column("LogSeverity", "string")
            .with_column("MaliciousIP", "string")
            .with_column("MaliciousIPCountry", "string")
            .with_column("MaliciousIPLatitude", "real")
            .with_column("MaliciousIPLongitude", "real")
            .with_column("Message", "string")
            .with_column("ProcessID", "int")
            .with_column("ProcessName", "string")
            .with_column("Protocol", "string")
            .with_column("Reason", "string")
            .with_column("ReceiptTime", "string")
            .with_column("ReceivedBytes", "long")
            .with_column("RemoteIP", "string")
            .with_column("RemotePort", "string")
            .with_column("RequestClientApplication", "string")
            .with_column("RequestContext", "string")
            .with_column("RequestCookies", "string")
            .with_column("RequestMethod", "string")
            .with_column("RequestURL", "string")
            .with_column("SentBytes", "long")
            .with_column("SimplifiedDeviceAction", "string")
            .with_column("SourceDnsDomain", "string")
            .with_column("SourceHostName", "string")
            .with_column("SourceIP", "string")
            .with_column("SourceMACAddress", "string")
            .with_column("SourceNTDomain", "string")
            .with_column("SourcePort", "int")
            .with_column("SourceProcessId", "int")
            .with_column("SourceProcessName", "string")
            .with_column("SourceServiceName", "string")
            .with_column("SourceSystem", "string")
            .with_column("SourceTranslatedAddress", "string")
            .with_column("SourceTranslatedPort", "int")
            .with_column("SourceUserID", "string")
            .with_column("SourceUserName", "string")
            .with_column("SourceUserPrivileges", "string")
            .with_column("StartTime", "datetime")
            .with_column("ThreatConfidence", "string")
            .with_column("ThreatDescription", "string")
            .with_column("ThreatSeverity", "int")
            .with_column("Type", "string")
            .with_column("_ResourceId", "string")
            .with_column("_SubscriptionId", "string"),
    );

    // Heartbeat - Agent heartbeat information
    tables.push(
        TableInfo::canonical("Heartbeat")
            .source("sentinel")
            .description(
                "Records logged by Log Analytics agents once per minute to report on agent health",
            )
            .column(time_col.clone())
            .with_column("Category", "string")
            .with_column("Computer", "string")
            .with_column("ComputerEnvironment", "string")
            .with_column("ComputerIP", "string")
            .with_column("ComputerPrivateIPs", "dynamic")
            .with_column("IsGatewayInstalled", "bool")
            .with_column("ManagementGroupName", "string")
            .with_column("OSMajorVersion", "string")
            .with_column("OSMinorVersion", "string")
            .with_column("OSName", "string")
            .with_column("OSType", "string")
            .with_column("RemoteIPCountry", "string")
            .with_column("RemoteIPLatitude", "real")
            .with_column("RemoteIPLongitude", "real")
            .with_column("Resource", "string")
            .with_column("ResourceGroup", "string")
            .with_column("ResourceId", "string")
            .with_column("ResourceProvider", "string")
            .with_column("ResourceType", "string")
            .with_column("SCAgentChannel", "string")
            .with_column("Solutions", "string")
            .with_column("SourceSystem", "string")
            .with_column("SubscriptionId", "string")
            .with_column("Type", "string")
            .with_column("Version", "string")
            .with_column("VMUUID", "string")
            .with_column("_ResourceId", "string")
            .with_column("_SubscriptionId", "string"),
    );

    // AuditLogs - Azure AD audit logs
    tables.push(
        TableInfo::canonical("AuditLogs")
            .source("sentinel")
            .description("Audit log for Azure Active Directory")
            .column(time_col.clone())
            .with_column("AADOperationType", "string")
            .with_column("AADTenantId", "string")
            .with_column("ActivityDateTime", "datetime")
            .with_column("ActivityDisplayName", "string")
            .with_column("AdditionalDetails", "dynamic")
            .with_column("Category", "string")
            .with_column("CorrelationId", "string")
            .with_column("DurationMs", "long")
            .with_column("Id", "string")
            .with_column("Identity", "string")
            .with_column("InitiatedBy", "dynamic")
            .with_column("Level", "string")
            .with_column("Location", "string")
            .with_column("LoggedByService", "string")
            .with_column("OperationName", "string")
            .with_column("OperationVersion", "string")
            .with_column("Resource", "string")
            .with_column("ResourceGroup", "string")
            .with_column("ResourceId", "string")
            .with_column("ResourceProvider", "string")
            .with_column("Result", "string")
            .with_column("ResultDescription", "string")
            .with_column("ResultReason", "string")
            .with_column("ResultSignature", "string")
            .with_column("ResultType", "string")
            .with_column("SourceSystem", "string")
            .with_column("TargetResources", "dynamic")
            .with_column("Type", "string"),
    );

    // OfficeActivity - Office 365 audit logs
    tables.push(
        TableInfo::canonical("OfficeActivity")
            .source("sentinel")
            .description(
                "Audit logs for Office 365 tenants including Exchange, SharePoint and Teams logs",
            )
            .column(time_col.clone())
            .column(tenant_col.clone())
            .with_column("AADGroupId", "string")
            .with_column("AADTarget", "string")
            .with_column("Activity", "string")
            .with_column("Actor", "string")
            .with_column("ActorContextId", "string")
            .with_column("ActorIpAddress", "string")
            .with_column("Application", "string")
            .with_column("ApplicationId", "string")
            .with_column("AzureActiveDirectory_EventType", "string")
            .with_column("ChannelGuid", "string")
            .with_column("ChannelName", "string")
            .with_column("ChannelType", "string")
            .with_column("ChatName", "string")
            .with_column("ChatThreadId", "string")
            .with_column("Client", "string")
            .with_column("ClientIP", "string")
            .with_column("ClientInfoString", "string")
            .with_column("ClientMachineName", "string")
            .with_column("ClientProcessName", "string")
            .with_column("ClientVersion", "string")
            .with_column("CrossMailboxOperations", "bool")
            .with_column("DestFolder", "string")
            .with_column("DestinationFileExtension", "string")
            .with_column("DestinationFileName", "string")
            .with_column("DestinationRelativeUrl", "string")
            .with_column("DestMailboxId", "string")
            .with_column("DestMailboxOwnerUPN", "string")
            .with_column("EventSource", "string")
            .with_column("ExtendedProperties", "string")
            .with_column("ExternalAccess", "string")
            .with_column("ExtraProperties", "dynamic")
            .with_column("Folder", "string")
            .with_column("Folders", "string")
            .with_column("InternalLogonType", "int")
            .with_column("InterSystemsId", "string")
            .with_column("IntraSystemId", "string")
            .with_column("IsManagedDevice", "bool")
            .with_column("Item", "string")
            .with_column("ItemName", "string")
            .with_column("ItemType", "string")
            .with_column("LoginStatus", "int")
            .with_column("Logon_Type", "string")
            .with_column("LogonUserDisplayName", "string")
            .with_column("LogonUserSid", "string")
            .with_column("MailboxGuid", "string")
            .with_column("MailboxOwnerMasterAccountSid", "string")
            .with_column("MailboxOwnerSid", "string")
            .with_column("MailboxOwnerUPN", "string")
            .with_column("Members", "dynamic")
            .with_column("MessageId", "string")
            .with_column("ModifiedObjectResolvedName", "string")
            .with_column("ModifiedProperties", "string")
            .with_column("Name", "string")
            .with_column("NewValue", "string")
            .with_column("OfficeId", "string")
            .with_column("OfficeObjectId", "string")
            .with_column("OfficeTenantId", "string")
            .with_column("OfficeWorkload", "string")
            .with_column("OldValue", "string")
            .with_column("Operation", "string")
            .with_column("OperationProperties", "dynamic")
            .with_column("OperationScope", "string")
            .with_column("OrganizationId", "string")
            .with_column("OrganizationName", "string")
            .with_column("OriginatingServer", "string")
            .with_column("Parameters", "string")
            .with_column("RecordType", "string")
            .with_column("ResultReasonType", "string")
            .with_column("ResultStatus", "string")
            .with_column("SensitivityLabelId", "string")
            .with_column("SharingType", "string")
            .with_column("Site_", "string")
            .with_column("Site_Url", "string")
            .with_column("Source_Name", "string")
            .with_column("SourceFileExtension", "string")
            .with_column("SourceFileName", "string")
            .with_column("SourceRecordId", "string")
            .with_column("SourceRelativeUrl", "string")
            .with_column("SourceSystem", "string")
            .with_column("Start_Time", "datetime")
            .with_column("TabType", "string")
            .with_column("TargetContextId", "string")
            .with_column("TargetUserId", "string")
            .with_column("TargetUserOrGroupName", "string")
            .with_column("TargetUserOrGroupType", "string")
            .with_column("TeamGuid", "string")
            .with_column("TeamName", "string")
            .with_column("Type", "string")
            .with_column("UniqueSharingId", "string")
            .with_column("UserAgent", "string")
            .with_column("UserDomain", "string")
            .with_column("UserId", "string")
            .with_column("UserKey", "string")
            .with_column("UserSharedWith", "string")
            .with_column("UserType", "string")
            .with_column("_ResourceId", "string")
            .with_column("_SubscriptionId", "string"),
    );

    // ThreatIntelligenceIndicator
    tables.push(
        TableInfo::canonical("ThreatIntelligenceIndicator")
            .source("sentinel")
            .description("Threat Intelligence Indicator")
            .column(time_col.clone())
            .column(tenant_col.clone())
            .with_column("Action", "string")
            .with_column("Active", "bool")
            .with_column("ActivityGroupNames", "string")
            .with_column("AdditionalInformation", "string")
            .with_column("ConfidenceScore", "real")
            .with_column("Description", "string")
            .with_column("DiamondModel", "string")
            .with_column("DomainName", "string")
            .with_column("EmailEncoding", "string")
            .with_column("EmailLanguage", "string")
            .with_column("EmailRecipient", "string")
            .with_column("EmailSenderAddress", "string")
            .with_column("EmailSenderName", "string")
            .with_column("EmailSourceDomain", "string")
            .with_column("EmailSourceIpAddress", "string")
            .with_column("EmailSubject", "string")
            .with_column("EmailXMailer", "string")
            .with_column("ExpirationDateTime", "datetime")
            .with_column("ExternalIndicatorId", "string")
            .with_column("FileCompileDateTime", "datetime")
            .with_column("FileCreatedDateTime", "datetime")
            .with_column("FileHashType", "string")
            .with_column("FileHashValue", "string")
            .with_column("FileMutexName", "string")
            .with_column("FileName", "string")
            .with_column("FilePacker", "string")
            .with_column("FilePath", "string")
            .with_column("FileSize", "int")
            .with_column("FileType", "string")
            .with_column("IndicatorId", "string")
            .with_column("IndicatorProvider", "string")
            .with_column("KillChainActions", "bool")
            .with_column("KillChainC2", "bool")
            .with_column("KillChainDelivery", "bool")
            .with_column("KillChainExploitation", "bool")
            .with_column("KillChainReconnaissance", "bool")
            .with_column("KillChainWeaponization", "bool")
            .with_column("KnownFalsePositives", "string")
            .with_column("MalwareNames", "string")
            .with_column("NetworkCidrBlock", "string")
            .with_column("NetworkDestinationAsn", "int")
            .with_column("NetworkDestinationCidrBlock", "string")
            .with_column("NetworkDestinationIP", "string")
            .with_column("NetworkDestinationPort", "int")
            .with_column("NetworkIP", "string")
            .with_column("NetworkPort", "int")
            .with_column("NetworkProtocol", "int")
            .with_column("NetworkSourceAsn", "int")
            .with_column("NetworkSourceCidrBlock", "string")
            .with_column("NetworkSourceIP", "string")
            .with_column("NetworkSourcePort", "int")
            .with_column("PassiveOnly", "bool")
            .with_column("SourceSystem", "string")
            .with_column("Tags", "string")
            .with_column("ThreatSeverity", "int")
            .with_column("ThreatType", "string")
            .with_column("TrafficLightProtocolLevel", "string")
            .with_column("Type", "string")
            .with_column("Url", "string")
            .with_column("UserAgent", "string"),
    );

    // SecurityAlert - Alerts from security products
    tables.push(
        TableInfo::canonical("SecurityAlert")
            .source("sentinel")
            .description("Alerts that have been generated by security products")
            .column(time_col.clone())
            .with_column("AlertLink", "string")
            .with_column("AlertName", "string")
            .with_column("AlertSeverity", "string")
            .with_column("AlertType", "string")
            .with_column("CompromisedEntity", "string")
            .with_column("ConfidenceLevel", "string")
            .with_column("ConfidenceScore", "real")
            .with_column("Description", "string")
            .with_column("DisplayName", "string")
            .with_column("EndTime", "datetime")
            .with_column("Entities", "string")
            .with_column("ExtendedLinks", "string")
            .with_column("ExtendedProperties", "string")
            .with_column("IsIncident", "bool")
            .with_column("ProcessingEndTime", "datetime")
            .with_column("ProductComponentName", "string")
            .with_column("ProductName", "string")
            .with_column("ProviderName", "string")
            .with_column("RemediationSteps", "string")
            .with_column("ResourceId", "string")
            .with_column("SourceComputerId", "string")
            .with_column("StartTime", "datetime")
            .with_column("Status", "string")
            .with_column("SubTechniques", "string")
            .with_column("SystemAlertId", "string")
            .with_column("Tactics", "string")
            .with_column("Techniques", "string")
            .with_column("Type", "string")
            .with_column("VendorName", "string")
            .with_column("VendorOriginalId", "string")
            .with_column("WorkspaceResourceGroup", "string")
            .with_column("WorkspaceSubscriptionId", "string"),
    );

    // SecurityIncident - Incidents from security products
    tables.push(
        TableInfo::canonical("SecurityIncident")
            .source("sentinel")
            .description("Incidents generated by security products")
            .column(time_col.clone())
            .column(tenant_col.clone())
            .with_column("AdditionalData", "dynamic")
            .with_column("AlertIds", "dynamic")
            .with_column("BookmarkIds", "dynamic")
            .with_column("Classification", "string")
            .with_column("ClassificationComment", "string")
            .with_column("ClassificationReason", "string")
            .with_column("ClosedTime", "datetime")
            .with_column("Comments", "dynamic")
            .with_column("CreatedTime", "datetime")
            .with_column("Description", "string")
            .with_column("FirstActivityTime", "datetime")
            .with_column("FirstModifiedTime", "datetime")
            .with_column("IncidentName", "string")
            .with_column("IncidentNumber", "int")
            .with_column("IncidentUrl", "string")
            .with_column("Labels", "dynamic")
            .with_column("LastActivityTime", "datetime")
            .with_column("LastModifiedTime", "datetime")
            .with_column("ModifiedBy", "string")
            .with_column("Owner", "dynamic")
            .with_column("ProviderIncidentId", "string")
            .with_column("ProviderName", "string")
            .with_column("RelatedAnalyticRuleIds", "dynamic")
            .with_column("Severity", "string")
            .with_column("SourceSystem", "string")
            .with_column("Status", "string")
            .with_column("Tasks", "dynamic")
            .with_column("Title", "string")
            .with_column("Type", "string"),
    );

    // DeviceEvents - Microsoft Defender for Endpoints events
    tables.push(
        TableInfo::canonical("DeviceEvents")
            .source("sentinel")
            .description("Microsoft Defender for Endpoints device events")
            .column(time_col.clone())
            .column(tenant_col.clone())
            .with_column("AccountDomain", "string")
            .with_column("AccountName", "string")
            .with_column("AccountSid", "string")
            .with_column("ActionType", "string")
            .with_column("AdditionalFields", "dynamic")
            .with_column("AppGuardContainerId", "string")
            .with_column("CreatedProcessSessionId", "long")
            .with_column("DeviceId", "string")
            .with_column("DeviceName", "string")
            .with_column("FileName", "string")
            .with_column("FileOriginIP", "string")
            .with_column("FileOriginUrl", "string")
            .with_column("FileSize", "long")
            .with_column("FolderPath", "string")
            .with_column("InitiatingProcessAccountDomain", "string")
            .with_column("InitiatingProcessAccountName", "string")
            .with_column("InitiatingProcessAccountObjectId", "string")
            .with_column("InitiatingProcessAccountSid", "string")
            .with_column("InitiatingProcessAccountUpn", "string")
            .with_column("InitiatingProcessCommandLine", "string")
            .with_column("InitiatingProcessCreationTime", "datetime")
            .with_column("InitiatingProcessFileName", "string")
            .with_column("InitiatingProcessFileSize", "long")
            .with_column("InitiatingProcessFolderPath", "string")
            .with_column("InitiatingProcessId", "long")
            .with_column("InitiatingProcessLogonId", "long")
            .with_column("InitiatingProcessMD5", "string")
            .with_column("InitiatingProcessParentCreationTime", "datetime")
            .with_column("InitiatingProcessParentFileName", "string")
            .with_column("InitiatingProcessParentId", "long")
            .with_column("InitiatingProcessRemoteSessionDeviceName", "string")
            .with_column("InitiatingProcessRemoteSessionIP", "string")
            .with_column("InitiatingProcessSessionId", "long")
            .with_column("InitiatingProcessSHA1", "string")
            .with_column("InitiatingProcessSHA256", "string")
            .with_column("InitiatingProcessUniqueId", "string")
            .with_column("InitiatingProcessVersionInfoCompanyName", "string")
            .with_column("InitiatingProcessVersionInfoFileDescription", "string")
            .with_column("InitiatingProcessVersionInfoInternalFileName", "string")
            .with_column("InitiatingProcessVersionInfoOriginalFileName", "string")
            .with_column("InitiatingProcessVersionInfoProductName", "string")
            .with_column("InitiatingProcessVersionInfoProductVersion", "string")
            .with_column("IsInitiatingProcessRemoteSession", "bool")
            .with_column("IsProcessRemoteSession", "bool")
            .with_column("LocalIP", "string")
            .with_column("LocalPort", "int")
            .with_column("LogonId", "long")
            .with_column("MachineGroup", "string")
            .with_column("MD5", "string")
            .with_column("ProcessCommandLine", "string")
            .with_column("ProcessCreationTime", "datetime")
            .with_column("ProcessId", "long")
            .with_column("ProcessRemoteSessionDeviceName", "string")
            .with_column("ProcessRemoteSessionIP", "string")
            .with_column("ProcessTokenElevation", "string")
            .with_column("RegistryKey", "string")
            .with_column("RegistryValueData", "string")
            .with_column("RegistryValueName", "string")
            .with_column("RemoteDeviceName", "string")
            .with_column("RemoteIP", "string")
            .with_column("RemotePort", "int")
            .with_column("RemoteUrl", "string")
            .with_column("ReportId", "long")
            .with_column("SHA1", "string")
            .with_column("SHA256", "string")
            .with_column("SourceSystem", "string")
            .with_column("Type", "string"),
    );

    // DeviceProcessEvents - MDE process events
    tables.push(
        TableInfo::canonical("DeviceProcessEvents")
            .source("sentinel")
            .description("Microsoft Defender for Endpoints device process events")
            .column(time_col.clone())
            .column(tenant_col.clone())
            .with_column("AccountDomain", "string")
            .with_column("AccountName", "string")
            .with_column("AccountObjectId", "string")
            .with_column("AccountSid", "string")
            .with_column("AccountUpn", "string")
            .with_column("ActionType", "string")
            .with_column("AdditionalFields", "dynamic")
            .with_column("AppGuardContainerId", "string")
            .with_column("CreatedProcessSessionId", "long")
            .with_column("DeviceId", "string")
            .with_column("DeviceName", "string")
            .with_column("FileName", "string")
            .with_column("FileSize", "long")
            .with_column("FolderPath", "string")
            .with_column("InitiatingProcessAccountDomain", "string")
            .with_column("InitiatingProcessAccountName", "string")
            .with_column("InitiatingProcessAccountObjectId", "string")
            .with_column("InitiatingProcessAccountSid", "string")
            .with_column("InitiatingProcessAccountUpn", "string")
            .with_column("InitiatingProcessCommandLine", "string")
            .with_column("InitiatingProcessCreationTime", "datetime")
            .with_column("InitiatingProcessFileName", "string")
            .with_column("InitiatingProcessFileSize", "long")
            .with_column("InitiatingProcessFolderPath", "string")
            .with_column("InitiatingProcessId", "long")
            .with_column("InitiatingProcessIntegrityLevel", "string")
            .with_column("InitiatingProcessLogonId", "long")
            .with_column("InitiatingProcessMD5", "string")
            .with_column("InitiatingProcessParentCreationTime", "datetime")
            .with_column("InitiatingProcessParentFileName", "string")
            .with_column("InitiatingProcessParentId", "long")
            .with_column("InitiatingProcessRemoteSessionDeviceName", "string")
            .with_column("InitiatingProcessRemoteSessionIP", "string")
            .with_column("InitiatingProcessSessionId", "long")
            .with_column("InitiatingProcessSHA1", "string")
            .with_column("InitiatingProcessSHA256", "string")
            .with_column("InitiatingProcessSignatureStatus", "string")
            .with_column("InitiatingProcessSignerType", "string")
            .with_column("InitiatingProcessTokenElevation", "string")
            .with_column("InitiatingProcessUniqueId", "string")
            .with_column("InitiatingProcessVersionInfoCompanyName", "string")
            .with_column("InitiatingProcessVersionInfoFileDescription", "string")
            .with_column("InitiatingProcessVersionInfoInternalFileName", "string")
            .with_column("InitiatingProcessVersionInfoOriginalFileName", "string")
            .with_column("InitiatingProcessVersionInfoProductName", "string")
            .with_column("InitiatingProcessVersionInfoProductVersion", "string")
            .with_column("IsInitiatingProcessRemoteSession", "bool")
            .with_column("IsProcessRemoteSession", "bool")
            .with_column("LogonId", "long")
            .with_column("MachineGroup", "string")
            .with_column("MD5", "string")
            .with_column("ProcessCommandLine", "string")
            .with_column("ProcessCreationTime", "datetime")
            .with_column("ProcessId", "long")
            .with_column("ProcessIntegrityLevel", "string")
            .with_column("ProcessRemoteSessionDeviceName", "string")
            .with_column("ProcessRemoteSessionIP", "string")
            .with_column("ProcessTokenElevation", "string")
            .with_column("ProcessUniqueId", "string")
            .with_column("ProcessVersionInfoCompanyName", "string")
            .with_column("ProcessVersionInfoFileDescription", "string")
            .with_column("ProcessVersionInfoInternalFileName", "string")
            .with_column("ProcessVersionInfoOriginalFileName", "string")
            .with_column("ProcessVersionInfoProductName", "string")
            .with_column("ProcessVersionInfoProductVersion", "string")
            .with_column("ReportId", "long")
            .with_column("SHA1", "string")
            .with_column("SHA256", "string")
            .with_column("SourceSystem", "string")
            .with_column("Type", "string"),
    );

    // DeviceNetworkEvents - MDE network events
    tables.push(
        TableInfo::canonical("DeviceNetworkEvents")
            .source("sentinel")
            .description("Microsoft Defender for Endpoints device network events")
            .column(time_col.clone())
            .column(tenant_col.clone())
            .with_column("ActionType", "string")
            .with_column("AdditionalFields", "dynamic")
            .with_column("AppGuardContainerId", "string")
            .with_column("DeviceId", "string")
            .with_column("DeviceName", "string")
            .with_column("InitiatingProcessAccountDomain", "string")
            .with_column("InitiatingProcessAccountName", "string")
            .with_column("InitiatingProcessAccountObjectId", "string")
            .with_column("InitiatingProcessAccountSid", "string")
            .with_column("InitiatingProcessAccountUpn", "string")
            .with_column("InitiatingProcessCommandLine", "string")
            .with_column("InitiatingProcessCreationTime", "datetime")
            .with_column("InitiatingProcessFileName", "string")
            .with_column("InitiatingProcessFileSize", "long")
            .with_column("InitiatingProcessFolderPath", "string")
            .with_column("InitiatingProcessId", "long")
            .with_column("InitiatingProcessIntegrityLevel", "string")
            .with_column("InitiatingProcessMD5", "string")
            .with_column("InitiatingProcessParentCreationTime", "datetime")
            .with_column("InitiatingProcessParentFileName", "string")
            .with_column("InitiatingProcessParentId", "long")
            .with_column("InitiatingProcessRemoteSessionDeviceName", "string")
            .with_column("InitiatingProcessRemoteSessionIP", "string")
            .with_column("InitiatingProcessSessionId", "long")
            .with_column("InitiatingProcessSHA1", "string")
            .with_column("InitiatingProcessSHA256", "string")
            .with_column("InitiatingProcessTokenElevation", "string")
            .with_column("InitiatingProcessUniqueId", "string")
            .with_column("InitiatingProcessVersionInfoCompanyName", "string")
            .with_column("InitiatingProcessVersionInfoFileDescription", "string")
            .with_column("InitiatingProcessVersionInfoInternalFileName", "string")
            .with_column("InitiatingProcessVersionInfoOriginalFileName", "string")
            .with_column("InitiatingProcessVersionInfoProductName", "string")
            .with_column("InitiatingProcessVersionInfoProductVersion", "string")
            .with_column("IsInitiatingProcessRemoteSession", "bool")
            .with_column("LocalIP", "string")
            .with_column("LocalIPType", "string")
            .with_column("LocalPort", "int")
            .with_column("MachineGroup", "string")
            .with_column("Protocol", "string")
            .with_column("RemoteIP", "string")
            .with_column("RemoteIPType", "string")
            .with_column("RemotePort", "int")
            .with_column("RemoteUrl", "string")
            .with_column("ReportId", "long")
            .with_column("SourceSystem", "string")
            .with_column("Type", "string"),
    );

    // DeviceFileEvents - MDE file events
    tables.push(
        TableInfo::canonical("DeviceFileEvents")
            .source("sentinel")
            .description("Microsoft Defender for Endpoints device file events")
            .column(time_col.clone())
            .column(tenant_col.clone())
            .with_column("ActionType", "string")
            .with_column("AdditionalFields", "dynamic")
            .with_column("AppGuardContainerId", "string")
            .with_column("DeviceId", "string")
            .with_column("DeviceName", "string")
            .with_column("FileName", "string")
            .with_column("FileOriginIP", "string")
            .with_column("FileOriginReferrerUrl", "string")
            .with_column("FileOriginUrl", "string")
            .with_column("FileSize", "long")
            .with_column("FolderPath", "string")
            .with_column("InitiatingProcessAccountDomain", "string")
            .with_column("InitiatingProcessAccountName", "string")
            .with_column("InitiatingProcessAccountObjectId", "string")
            .with_column("InitiatingProcessAccountSid", "string")
            .with_column("InitiatingProcessAccountUpn", "string")
            .with_column("InitiatingProcessCommandLine", "string")
            .with_column("InitiatingProcessCreationTime", "datetime")
            .with_column("InitiatingProcessFileName", "string")
            .with_column("InitiatingProcessFileSize", "long")
            .with_column("InitiatingProcessFolderPath", "string")
            .with_column("InitiatingProcessId", "long")
            .with_column("InitiatingProcessIntegrityLevel", "string")
            .with_column("InitiatingProcessMD5", "string")
            .with_column("InitiatingProcessParentCreationTime", "datetime")
            .with_column("InitiatingProcessParentFileName", "string")
            .with_column("InitiatingProcessParentId", "long")
            .with_column("InitiatingProcessRemoteSessionDeviceName", "string")
            .with_column("InitiatingProcessRemoteSessionIP", "string")
            .with_column("InitiatingProcessSessionId", "long")
            .with_column("InitiatingProcessSHA1", "string")
            .with_column("InitiatingProcessSHA256", "string")
            .with_column("InitiatingProcessTokenElevation", "string")
            .with_column("InitiatingProcessUniqueId", "string")
            .with_column("InitiatingProcessVersionInfoCompanyName", "string")
            .with_column("InitiatingProcessVersionInfoFileDescription", "string")
            .with_column("InitiatingProcessVersionInfoInternalFileName", "string")
            .with_column("InitiatingProcessVersionInfoOriginalFileName", "string")
            .with_column("InitiatingProcessVersionInfoProductName", "string")
            .with_column("InitiatingProcessVersionInfoProductVersion", "string")
            .with_column("IsAzureInfoProtectionApplied", "bool")
            .with_column("IsInitiatingProcessRemoteSession", "bool")
            .with_column("MachineGroup", "string")
            .with_column("MD5", "string")
            .with_column("PreviousFileName", "string")
            .with_column("PreviousFolderPath", "string")
            .with_column("ReportId", "long")
            .with_column("RequestAccountDomain", "string")
            .with_column("RequestAccountName", "string")
            .with_column("RequestAccountSid", "string")
            .with_column("RequestProtocol", "string")
            .with_column("RequestSourceIP", "string")
            .with_column("RequestSourcePort", "int")
            .with_column("SensitivityLabel", "string")
            .with_column("SensitivitySubLabel", "string")
            .with_column("SHA1", "string")
            .with_column("SHA256", "string")
            .with_column("ShareName", "string")
            .with_column("SourceSystem", "string")
            .with_column("Type", "string"),
    );

    // EmailEvents - Office 365 email events
    tables.push(
        TableInfo::canonical("EmailEvents")
            .source("sentinel")
            .description("Office 365 email events, including email delivery and blocking events")
            .column(time_col.clone())
            .column(tenant_col.clone())
            .with_column("AdditionalFields", "dynamic")
            .with_column("AttachmentCount", "int")
            .with_column("AuthenticationDetails", "string")
            .with_column("BulkComplaintLevel", "int")
            .with_column("Cc", "dynamic")
            .with_column("ConfidenceLevel", "string")
            .with_column("Connectors", "string")
            .with_column("Context", "string")
            .with_column("DeliveryAction", "string")
            .with_column("DeliveryLocation", "string")
            .with_column("DetectionMethods", "string")
            .with_column("DistributionList", "string")
            .with_column("EmailAction", "string")
            .with_column("EmailActionPolicy", "string")
            .with_column("EmailActionPolicyGuid", "string")
            .with_column("EmailClusterId", "long")
            .with_column("EmailDirection", "string")
            .with_column("EmailLanguage", "string")
            .with_column("EmailSize", "int")
            .with_column("ExchangeTransportRule", "string")
            .with_column("ForwardingInformation", "string")
            .with_column("InternetMessageId", "string")
            .with_column("IsFirstContact", "bool")
            .with_column("LatestDeliveryAction", "string")
            .with_column("LatestDeliveryLocation", "string")
            .with_column("NetworkMessageId", "string")
            .with_column("OrgLevelAction", "string")
            .with_column("OrgLevelPolicy", "string")
            .with_column("RecipientDomain", "string")
            .with_column("RecipientEmailAddress", "string")
            .with_column("RecipientObjectId", "string")
            .with_column("ReportId", "string")
            .with_column("SenderDisplayName", "string")
            .with_column("SenderFromAddress", "string")
            .with_column("SenderFromDomain", "string")
            .with_column("SenderIPv4", "string")
            .with_column("SenderIPv6", "string")
            .with_column("SenderMailFromAddress", "string")
            .with_column("SenderMailFromDomain", "string")
            .with_column("SenderObjectId", "string")
            .with_column("SourceSystem", "string")
            .with_column("Subject", "string")
            .with_column("ThreatClassification", "string")
            .with_column("ThreatNames", "string")
            .with_column("ThreatTypes", "string")
            .with_column("To", "dynamic")
            .with_column("Type", "string")
            .with_column("UrlCount", "int")
            .with_column("UserLevelAction", "string")
            .with_column("UserLevelPolicy", "string"),
    );

    info!("Loaded {} default table schemas", tables.len());
    tables
}
